dist: bionic

services:
  - docker

cache:
  pip: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
    - python3-pip
    - python3-setuptools

before_script:
  # build docker images
  - sudo docker-compose -f local.yml build
  - sudo docker-compose -f production.yml build

install:
  # install docker-compose
  - pip3 install docker-compose wheel

script:
  - sudo docker-compose -f local.yml run django pytest
  - sudo docker-compose -f production.yml run django pytest