dist: bionic

language: python

os:
  - linux

services:
  - docker

cache:
  pip: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
    - python3-pip
    - python3-setuptools

before_script:
  # build docker images development
  - sudo docker-compose -f local.yml build
  # build docker images production
  - cp -r .envs/.local/ .envs/.production/
  - sudo docker-compose -f production.yml build
  # add test groups for group import command
  - cp compose/local/django/meetup_groups/test-groups.json meetup_groups/test-groups.json

install:
  # install docker-compose
  - pip3 install docker-compose wheel

script:
  # run tests
  - sudo docker-compose -f local.yml run django coverage run -m pytest
  # test commands
  - sudo docker-compose -f local.yml run django python manage.py migrate
  - sudo docker-compose -f local.yml run django python manage.py update_group --sandbox
  - sudo docker-compose -f local.yml run django python manage.py get_groups --json_path /app/compose/local/django/meetup_groups
  - sudo docker-compose -f local.yml run django python manage.py update_index

# code coverage
after_success:
  - echo TRAVIS_JOB_ID=$TRAVIS_JOB_ID >> .envs/.local/.django
  - echo TRAVIS_BRANCH=$TRAVIS_BRANCH >> .envs/.local/.django
  - echo COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN >> .envs/.local/.django
  - sudo docker-compose -f local.yml run django coverage report
  - sudo docker-compose -f local.yml run django coveralls