version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_elasticsearch_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: meetup_data_scraper_local_django
    depends_on:
      - postgres
      - elasticsearch
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.elasticsearch
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: meetup_data_scraper_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  elasticsearch:
    image: elasticsearch:7.5.0
    volumes:
      - local_elasticsearch_data:/usr/share/elasticsearch/data
    env_file:
      - ./.envs/.local/.elasticsearch
    restart: always
